// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitializeGeneratedByWire() (*D, error) {
	a, err := NewA()
	if err != nil {
		return nil, err
	}
	b := NewB(a)
	c := NewC()
	d, err := NewD(b, c)
	if err != nil {
		return nil, err
	}
	return d, nil
}
