name: Deploy Game to GitHub Pages

on:
  push:
    branches: [ master ]
    paths:
      - 'ai-generated-something/roo-cline/vampire-survivors-like/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Build WASM
        run: |
          cd ai-generated-something/roo-cline/vampire-survivors-like
          GOOS=js GOARCH=wasm go build -o public/main.wasm
          cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ai-generated-something/roo-cline/vampire-survivors-like/public
          destination_dir: vampire-survivors-like